language: node_js
sudo: false
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_6c266e67b443_key -iv $encrypted_6c266e67b443_iv -in .travis/govuk_frontend_toolkit_npm_push.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git remote add origin_ssh git@github.com:alphagov/govuk_frontend_toolkit_npm.git
script:
  - ./publish.sh
deploy:
  provider: npm
  email: govuk-dev@digital.cabinet-office.gov.uk
  api_key:
    secure: JNPzkjCkl3YF52/OPsu6PNZ4T5hCoBrqVAygpp4+VNs2//18hYkTRFiA0xSLDab8JBOp6lb9Ukqp2mjZh50zPKyc8Vd98cYrG5Wmbi/79lQwfX4AuQ9yAq7tgdMicvjQcyvbDK1uwPpQ56uiCTx4O4hNftWe1CJBrYY0xbzs1KA=
  on:
    branch: master
