language: node_js
sudo: false
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_6c266e67b443_key -iv $encrypted_6c266e67b443_iv -in .travis/govuk_frontend_toolkit_npm_push.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git remote add origin_ssh git@github.com:alphagov/govuk_frontend_toolkit_npm.git
install:
  - echo "No dependencies to install"
script:
  - ./publish.sh
deploy:
  provider: npm
  emai: govuk-dev@digital.cabinet-office.gov.uk
  api_key:
    secure: lQumjzh4nXch5pVm3KopTlso+PBLAiEhiq1mLmp7Au2L5KnRI06FiLwoBEgDodDMPA6XHdd2Yhrzs8hlufgIYtcJOwfGbv2uTz/kOgXkdpjsUOpQgekZ1wTKNjBdJEmHX9AGhwckfvi5y14bRNQYUyXNpv75MC4xph/pbImKt3w=
  on:
    branch: master
